=== sevcanmehmed/XML-Project/healthy-food-catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT healthy-food-catalog (foods)>
        <!ELEMENT foods (food+)>
        <!ELEMENT food (name, image, category, price, benefits texture expire-date flavour, appearance,  nutritional-content, recipe, ethical-production) >
           <!ELEMENT name (#PCDATA)>
           <!ELEMENT image (#PCDATA)>
           <!ELEMENT category (#PCDATA)>
           <!ELEMENT benefits (#PCDATA)>
           <!ELEMENT price (#PCDATA)>
           <!ELEMENT texture (#PCDATA)>
            <!ELEMENT consistency (#PCDATA)>
           <!ELEMENT expire-date (#PCDATA)>
           <!ELEMENT flavour (#PCDATA)>
           <!ELEMENT appearance (size, shape, color)>
               <!ELEMENT size (#PCDATA)>
               <!ELEMENT shape (#PCDATA)>
               <!ELEMENT color (#PCDATA)>
            <!ELEMENT nutritional-content (calories, carbs, fat, protein, vitamin)>
               <!ELEMENT calories (#PCDATA)>
               <!ELEMENT carbs (#PCDATA)>
               <!ELEMENT fat (#PCDATA)>
               <!ELEMENT protein (#PCDATA)>
               <!ELEMENT vitamin (#PCDATA)>
            <!ELEMENT recipe (products,preparation,time)>
                 <!ELEMENT products (#PCDATA)>
                 <!ELEMENT preparation (#PCDATA)>
                 <!ELEMENT time (#PCDATA)>
            <!ELEMENT ethical-production (country)>
              <!ELEMENT country (#PCDATA)>

 <!ATTLIST category type (Зърнен|Млечен|Плод|Зеленчук|Месо|Бобови) #REQUIRED>
<!ATTLIST carbs sugars CDATA #REQUIRED>
<!ATTLIST fat saturated CDATA #REQUIRED>
<!ATTLIST vitamin quantity CDATA #REQUIRED>
<!ATTLIST country part CDATA #REQUIRED>
<!ATTLIST flavour alterntive CDATA #REQUIRED>
<!ATTLIST price grams CDATA #REQUIRED>
<!ATTLIST expire-date storage (рафт|хладилник) #REQUIRED>
<!ATTLIST nutritional-content size CDATA #REQUIRED>
<!ATTLIST recipe name CDATA #REQUIRED>

=== sevcanmehmed/XML-Project/Valid_XML_2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE healthy-food-catalog SYSTEM "healthy-food-catalog.dtd">
<?xml-stylesheet type="text/xsl" href="html_transformation4.xsl"?>

<healthy-food-catalog>
    <foods>
        <food>
            <name>Броколи</name>
            <image>broccoli.jpg</image>
            <category type="Зеленчук"/>
            <benefits> 1.Намаляват възпаленията.
                2.Предпазват срещу някои видове рак.
                3.Поддържат здравето на сърцето.
                4.Подобряват храносмилането и намаляват запека.
                5.Поддържат здрава умствена функция.
                6.Забавят процеса на стареене.
            </benefits>
            <price grams="500g">2.30лв</price>
            <texture>Листата - меки, стъблата и дръжките - твърди</texture>
            <consistency>Хрупкави</consistency>
            <expire-date storage="хладилник">1-2 седмици</expire-date>
            <flavour alternative="мек">приятен</flavour>
            <appearance>
                <size>60-90см.</size>
                <shape>дървовидна</shape>
                <color>тъмно зелен</color>
            </appearance>
            <nutritional-content size="500g">
                <calories>170</calories>
                <carbs sugars="7.5g">20g</carbs>
                <fat saturated="0.2g">2g</fat>
                <protein>14g</protein>
                <vitamin quantity="25%">C</vitamin>
            </nutritional-content>
            <recipe name="Задушени броколи със сирене">
                <products>
                    броколи - 1 глава
                    краве масло - 35 г
                    зехтин - 2 с.л.
                    прясно мляко - 1 к.ч.
                    чесън - 1 - 2 скилидки
                    сирене - 200 г
                    чери домати - 200 г
                    сол - на вкус
                    черен пипер - на вкус (по желание)
                    лимонов сок - от 1/2 лимон
                </products>
                <preparation>
                    Загрейте вода на силен огън с лъжица зехтин или олио и малко сол.
                    Разчленете броколите на розички, измийте и бланширайте във врящата вода.
                    Сипете млякото, за да омекоти вкуса на зеленчука.
                    Броколите трябва леко да омекнат, а не да се сварят.
                    Извадете ги с решетъчна лъжица и пуснете в тиган с разтопеното масло, малко зехтин, сол и накълцана скилидка - две чесън. Задушете под капак за 10 минути, като сипете и малко от бульона от варенето.
                    Зеленчукът е хубаво да остане меко хрупкав, не да се разпада. Той ще си поеме маслото и аромата на чесън.
                    Разпределете на порции и към броколите нарежете чери домати.
                    Поръсете с черен пипер по желание, малко лимонов сок и отгоре натрошете сирене.
                    Би било хубаво и ако леко се запече в загрята на 200 градуса фурна, но и без това се получава страхотно.
                    Сервирайте топли, задушените броколи с полуразтопеното от топлината сирене върху тях.
                </preparation>
                <time>
                    30-40 минути
                </time>
            </recipe>
            <ethical-production>
                <country part="Средиземноморски регион">Италия</country>
            </ethical-production>
        </food>

    </foods>


</healthy-food-catalog>

=== sevcanmehmed/XML-Project/Valid_XML_4.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE healthy-food-catalog SYSTEM "healthy-food-catalog.dtd">
<?xml-stylesheet type="text/xsl" href="html_transformation4.xsl"?>

<healthy-food-catalog>
    <foods>
        <food>
            <name>Сьомга</name>
            <image>salmon.jpg</image>
            <category type="Месо"/>
            <benefits> 1.Намалява риска от сърдечни заболявания.
                2.Защитава здравето на мозъка.
                3.Богата на омега-3 мастни киселини.
                4.Пълна с антиоксиданти.
                5.Тя е от решаващо значение за имунитета.
                6.Тя е ключът за здрави кости.
            </benefits>
            <price grams="210g">9.16лв</price>
            <texture>Мека</texture>
            <consistency>Влажна</consistency>
            <expire-date storage="хладилник">1-2 дена</expire-date>
            <flavour alternative="ароматен">Мазен</flavour>
            <appearance>
                <size>0.5-1.5м.</size>
                <shape>продълговата, странично сплескано тяло</shape>
                <color>розово-оранжева</color>
            </appearance>
            <nutritional-content size="210g">
                <calories>392</calories>
                <carbs sugars="0g">0g</carbs>
                <fat saturated="5g">24g</fat>
                <protein>42g</protein>
                <vitamin quantity="14%">C</vitamin>
            </nutritional-content>
            <recipe name="Маринована сьомга с чесън и соев сос">
                <products>
                    6 бр филета от сьомга
                    1 скилидка чесън
                    ½ чаша кафява захар
                    ½ чаша олио/зехтин
                    ½ чаша вода
                    ½ чаша соев сос
                    1 щипка сол
                    1 щипка черен пипер
                    1 лимон за изстискване
                </products>
                <preparation>
                    За да направите маринатата смесете соевия сос, мазнината, подправките, наситнения чесън, изстискания лимонов сок, захарта и водата.
                    Разбъркайте добре и потопете филетата в маринатата.
                    Оставете така в хладилника за няколко часа.
                    Загрейте мазнина в тигана на средна температура.
                    Запържете сьомгата от всяка страна по няколко минути.
                    По този начин рибата може да се приготви и на скара.
                </preparation>
                <time>
                    3-4 часа
                </time>
            </recipe>
            <ethical-production>
                <country part="Централна">Норвегия</country>
            </ethical-production>
        </food>

    </foods>


</healthy-food-catalog>

=== sevcanmehmed/XML-Project/Valid_XML_1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="html_transformation4.xsl"?>
<!DOCTYPE healthy-food-catalog SYSTEM "healthy-food-catalog.dtd">

<healthy-food-catalog>
   <foods>
       <food>
          <name>Авокадо</name>
           <image>avocado.jpg</image>
           <category type="Плод"/>
           <benefits> 1. Намалява риска от сърдечносъдови заболявания.
                      2. Екстракт от авокадо подпомага за облекчаване на симптомите на артрит.
                      3. Мазнините в авокадото помагат да се абсорбират хранителните вещества от растителните храни.
                      4. Помага в борбата с килограмите
                      5. Предпазва от рак
                      6. Въздейства благотворно върху кожата и очите
           </benefits>
           <price grams="200g">2.48лв</price>
           <texture>Кремообразна</texture>
           <consistency>Мека</consistency>
           <expire-date storage="хладилник">7-10 дни</expire-date>
           <flavour alternative="маслен">Орехов</flavour>
           <appearance>
               <size>7-10см.</size>
               <shape>крушовидна, продълговата</shape>
               <color>тъмно зелен</color>
           </appearance>
           <nutritional-content size="200g">
               <calories>322</calories>
               <carbs sugars="1g">17g</carbs>
               <fat saturated="4g">29g</fat>
               <protein>4g</protein>
               <vitamin quantity="33%">C</vitamin>
           </nutritional-content>
           <recipe name="сандвич с авокадо">
               <products>
                   авокадо - 2 бр.
                   червен лук - 1 бр.
                   домати - 1/2 бр.
                   лимон - 1/2 бр.
                   зехтин - на вкус
                   сол - на вкус
               </products>
               <preparation>
                   Обелваме авокадото, като е хубаво да е добре узряло.
                   Намачкваме го с вилица до получаването на хомогенна смес. Нарязваме на ситно лука и домата. Смесваме всичко е овкусяваме със зехтин и сол.
                   Препичаме филийки пълнозърнест хляб и ги намазваме с готовата смес.
                   Чудесно предястие, както и междинна закуска.
               </preparation>
               <time>
                   10-15 минути
               </time>
           </recipe>
           <ethical-production>
               <country part="Централна">Америка</country>
           </ethical-production>
       </food>

   </foods>


</healthy-food-catalog>

=== sevcanmehmed/XML-Project/Valid_XML_3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE healthy-food-catalog SYSTEM "healthy-food-catalog.dtd">
<?xml-stylesheet type="text/xsl" href="html_transformation4.xsl"?>

<healthy-food-catalog>
    <foods>
        <food>
            <name>Леща</name>
            <image>lentils.jpg</image>
            <category type="Бобови"/>
            <benefits> 1. Понижава холестерола.
                2.Поддържа здравето на сърцето.
                3. Подпомага храносмилането.
                4. Здравословен източник на протеин.
                5. Увеличава енергията
                6. Подпомага отслабването.
            </benefits>
            <price grams="500g">1.75лв</price>
            <texture>Твърда</texture>
            <consistency>Крехка</consistency>
            <expire-date storage="рафт">1-2 години</expire-date>
            <flavour alternative="сладка">Земен вкус</flavour>
            <appearance>
                <size>0.5см.</size>
                <shape>заоблена, надута</shape>
                <color>кафяв,зелен, червен</color>
            </appearance>
            <nutritional-content size="500g">
                <calories>580</calories>
                <carbs sugars="9g">100g</carbs>
                <fat saturated="0.5g">2g</fat>
                <protein>45g</protein>
                <vitamin quantity="12.5%">C</vitamin>
            </nutritional-content>
            <recipe name="Супа от зеленчуци и леща">
                <products>
                    лук - 1 глава, кромид
                    чесън - 2 скилидки, на ситно
                    леща - 5 ч.ч. (500 г), зелена
                    домати - 1 бр., обелен, нарязан едро
                    сол, черен пипер - на вкус
                    бульон - 1 кубче, зеленчуков
                    вода - 1, 5 л
                    картофи - 2 бр., на кубчета
                    моркови - 2 бр., на кубчета
                </products>
                <preparation>
                    Лукът и чесънът се запържват около 5 мин. Добавят се лещата и доматът. Осолява се и се поръсва с черен пипер.
                    Добавя се кубчето бульон и водата. След 15 мин. се прибавят картофите, морковите и се варят още 15 мин.
                    Поднася се топла с хляб.
                </preparation>
                <time>
                    25-30 минути
                </time>
            </recipe>
            <ethical-production>
                <country part="централна">Америка</country>
            </ethical-production>
        </food>

    </foods>


</healthy-food-catalog>
